OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
#RGBLIGHT_ENABLE = yes
LTO_ENABLE = yes
#WPM_ENABLE = yes
#VIA_ENABLE = yes
TAP_DANCE_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812

